version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - --bind
      - djangoProject.wsgi
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "200k"
    volumes:
      - ./djangoProject/database:/app/database